AllCops:
  TargetRubyVersion: 2.2.6
  Exclude:
    - db/schema.rb
    - out/**/*
    - tmp/**/*
    - spec/dummy/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/initializers/**/*
    - lib/spree_drop_ship/factories.rb
    - lib/tasks/**/*
    - spec/**/*
    - spree_drop_ship.gemspec